apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: deployment-secrets
  namespace: ixn
stringData:
  POSTGRES_ADDR: pgdb-dgt-postgresql.infra.svc.cluster.local
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: INSERT_POSTGRES_PASSWORD
  IXN_DB: ixn-100
  IXN_NODE_DB: ixn-node-100
  ixn_db_user: ixn
  ixn_db_password: INSERT_IXN_DB_PASSWORD
  redis_password: INSERT_REDIS_PASSWORD
  tenant_sid: "100"
  tenant_id: 9350e2fc-a1dd-4c65-8d40-1f75a2e080dd