apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: deployment-secrets
  namespace: gauth
stringData:
  POSTGRES_ADDR: pgdb-gws-postgresql.infra.svc.cluster.local
  POSTGRES_USER: 	postgres
  POSTGRES_PASSWORD: INSERT_POSTGRES_PASSWORD
  DB_NAME: gauth
  gauth_pg_username: gauth_pg_user
  gauth_pg_password: INSERT_GAUTH_PG_PASSWORD
  gauth_redis_password: INSERT_REDIS_PASSWORD
  gauth_admin_username: gauth_admin_user
  gauth_admin_password: INSERT_GAUTH_ADMIN_PASSWORD
  gauth_gws_client_id: gauth_client
  gauth_gws_client_secret: INSERT_GAUTH_GWS_CLIENT_SECRET
  gauth_jks_keyPassword: INSERT_GAUTH_JKS_KEYPASSWORD
  gauth_jks_keyStorePassword: INSERT_JKS_KEYSTOREPASSWORD
  LOCATION: /USW2