apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: deployment-secrets
  namespace: gws
stringData:
  gws_redis_password: INSERT_REDIS_PASSWORD
  gws_consul_token: INSERT_CONSUL_TOKEN
  POSTGRES_ADDR: pgdb-gws-postgresql.infra.svc.cluster.local
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: INSERT_POSTGRES_PASSWORD
  gws_pg_user: gws_pg_user
  gws_pg_pass: INSERT_PG_PASSWORD
  gws_as_pg_user: gws_as_user
  gws_as_pg_pass: INSERT_AS_PG_PASSWORD
  gws_app_provisioning: A34BOmXDedZwbTKrwmd4eA==
  gws_app_workspace: A34BOmXDedZwbTKrwmd4eA==
  gws_client_id: external_api_client
  gws_client_secret: INSERT_CLIENT_SECRET
  gws_ops_user: ops
  gws_ops_pass_encr: INSERT_OPS_PASSWORD
  DB_NAME_GWS: gws
  DB_NAME_PROV: prov
  ES_ADDR: opensearch-cluster-master.infra.svc.cluster.local
  REDIS_ADDR: infra-redis-redis-cluster.infra.svc.cluster.local
  global_location: /USW2