apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: deployment-secrets
  namespace: voice
stringData:
  CONSUL_VOICE_TOKEN: INSERT_CONSUL_TOKEN
  POSTGRES_ADDR: pgdb-std-postgresql.infra.svc.cluster.local
  POSTGRES_USER: 	postgres
  POSTGRES_PASSWORD: INSERT_POSTGRES_PASSWORD
  DNS_SERVER: INSERT_DNS
  KAFKA_ADDRESS: kafka-helm-cp-kafka.kafka.svc.cluster.local:9092
  REDIS_IP: INSERT_REDIS_IP
  REDIS_PASSWORD: INSERT_REDIS_PASSWORD
  REDIS_PORT: "6379"
  tenant_gauth_client_id: external_api_client
  tenant_gauth_client_secret: INSERT_TENANT_CLIENT_SECRET
  tenant_t100_pg_db_name: t100
  tenant_t100_pg_db_user: t100
  tenant_t100_pg_db_password: INSERT_TENANT_PG_DB_PASSWORD
  LOCATION: USW2