apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: deployment-secrets
  namespace: iwddm
stringData:
  POSTGRES_ADDR: pgdb-rpthist-postgresql.infra
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: INSERT_POSTGRES_PASSWORD
  gcxi_db_user: gcxi
  gcxi_db_password: INSERT_GCXI_DB_PASSWORD
  gim_db_user: gim
  gim_db_password: INSERT_GIM_DB_PASSWORD
  iwddm_db_user: iwddm-100
  iwddm_db_password: INSERT_IWDDM_PASSWORD
  iwddm_nexus_api_key: INSERT_IWDDM_NEXUS_API_KEY
  tenant_sid: "100"