apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: deployment-secrets
  namespace: gim
stringData:
  gim_pgdb_server: pgdb-rpthist-postgresql.infra.svc.cluster.local
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: INSERT_POSTGRES_PASSWORD
  gim_pgdb_etl_name: gim
  gim_pgdb_etl_password: INSERT_GIM_PGDB_ETL_PASSWORD
  gim_pgdb_etl_user: gim
  gim_pgdb_port: "5432"
  tenant_id: 9350e2fc-a1dd-4c65-8d40-1f75a2e080dd
  tenant_sid: "100"
  KAFKA_ADDR: kafka-helm-cp-kafka.kafka.svc.cluster.local