apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: deployment-secrets
  namespace: gvp
stringData:
  POSTGRES_USER: 	postgres
  POSTGRES_PASSWORD: INSERT_POSTGRES_PASSWORD
  gvp_cm_configserver_user: default
  gvp_cm_configserver_password: INSERT_GVP_CM_CONFIGSERVER_PASSWORD
  gvp_pg_db_server: pgdb-std-postgresql.infra.svc.cluster.local
  gvp_cm_pg_db_name: gvp
  gvp_cm_pg_db_user: gvp
  gvp_cm_pg_db_password: INSERT_GVP_CM_PG_DB_PASSWORD
  gvp_consul_token: INSERT_CONSUL_TOKEN
  gvp_mssql_db_server: mssqlserver-2019.infra.svc.cluster.local
  gvp_rs_mssql_db_name: gvp_rs
  gvp_rs_mssql_db_user: gkeadmin
  gvp_rs_mssql_db_password: INSERT_GVP_RS_MSSQL_DB_PASSWORD
  gvp_rs_mssql_admin_password: INSERT_GVP_RS_MSSQL_ADMIN_PASSWORD
  gvp_rs_mssql_reader_password: INSERT_GVP_RS_MSSQL_READER_PASSWORD